### ISSUE TITLE
plugin [id: 'org.springframework.boot', version: '2.6.8'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by superkaiy** [fosslight/fosslight#584] opened 2022-07-19 06:44 UTC
**Describe the bug**
execute command: docker-compose up --build, will meet the following errors:
**plugin [id: 'org.springframework.boot', version: '2.6.8'] was not found in any of the following sources:**

docker version: Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
docker-compose version: docker-compose version 1.25.0

**To Reproduce**
just execute command "docker-compose up --build" to install fosslight

**Expected behavior**

**Screenshots**

**System Environment (please complete the following information):**
 - docker version: Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
 - docker-compose version: docker-compose version 1.25.0
 - Ubuntu 20.04

**Additional context**

**Comment by soimkim** [comment] 2022-07-20 07:24
@superkaiy , It seems to be a duplicate issue with https://github.com/fosslight/fosslight/issues/585.
In case of duplicate, one issue will be closed.

**Comment by superkaiy** [comment] 2022-07-20 07:50
@soimkim Yes, I'm sorry for that it's a duplicated issue for misoperation。

**Comment by superkaiy** [comment] 2022-07-25 02:32
@soimkim any update? I mean installation is quite inconvenient if the issue still exists

**Comment by superkaiy** [comment] 2022-07-25 06:49
@soimkim I doubt that there is something wrong with build.gradle

![Screenshot from 2022-07-25 14-42-30](https://user-images.githubusercontent.com/45934483/180714696-89ad680c-b594-48b6-a674-dc6f2f7d92d8.png)
![Screenshot from 2022-07-25 14-46-32](https://user-images.githubusercontent.com/45934483/180715071-cab1885b-1f28-417e-bf86-64318ba1162c.png)

**Comment by soimkim** [comment] 2022-07-25 06:57
@superkaiy , tell me your build command.
Do you run only the db service with docker and do the build separately?

**Comment by soimkim** [comment] 2022-07-25 07:21
It is not reproduced in my environment.
- Ubuntu 20.04
```
soim@soim-14Z980-GPLGL:~/git/fosslight$ docker -v
Docker version 20.10.17, build 100c701
soim@soim-14Z980-GPLGL:~/git/fosslight$ docker-compose -v
docker-compose version 1.25.0-rc2, build 661ac20e
```
- build & run command : `docker-compose up --build`

**Comment by superkaiy** [comment] 2022-07-25 07:23
@soimkim I found there was some error during building web image when used command "docker-compose up --build".
![Screenshot from 2022-07-25 15-21-49](https://user-images.githubusercontent.com/45934483/180720666-19168f84-9048-4ae8-97e3-efcc4f0b74ce.png)
So I tried to build just web image to do some test about gradle environment with command: docker pull gradle:6.8.2-jdk11 & docker run --rm -it -u gradle -v "$PWD":/home/gradle/project gradle:6.8.2-jdk11 bash. And execute "gradle build" in the web containter

./gradlew build -x test:

**Comment by soimkim** [comment] 2022-07-25 07:36
🤔 Hmm....It is difficult to reproduce...
Could you please refer to this link to solve it? (It is in Korean)
- https://da2uns2.tistory.com/entry/Spring-Boot-Plugin-id-orgspringframeworkboot-version-256-was-not-found-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0

**Comment by superkaiy** [comment] 2022-07-26 02:23
@soimkim Many thanks. It seems no help. 
Could you help to build the official web app image and upload to Docker hub?
It will cut down issues about environment.

**Comment by soimkim** [comment] 2022-07-26 04:15
@superkaiy ,
Docker image distribution is registered as a separate issue. : https://github.com/fosslight/fosslight/issues/601
Maybe it will take some time for F/U.

I will close this issue because there is no more F/U to do.

**Closed by soimkim** 2022-07-26 04:15 UTC
Labels: bug
